# Generated by Django 4.0.5 on 2022-06-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_incident_actor_options_remove_incident_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='area',
        ),
        migrations.AddField(
            model_name='incident',
            name='area_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.distrcit_city'),
        ),
        migrations.AddField(
            model_name='incident',
            name='area_subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.sub_district'),
        ),
        migrations.AddField(
            model_name='incident',
            name='area_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.village'),
        ),
    ]
