# Generated by Django 4.0.5 on 2022-06-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_incident_area_incident_area_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='Infra_damage',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='Infra_destroyed',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='child_death',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='child_injured',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='covid_rel',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='death_injured',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='fem_death',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='fem_injured',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='num_death',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='num_injured',
        ),
        migrations.CreateModel(
            name='Incident_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_rel', models.PositiveBigIntegerField(null=True)),
                ('num_death', models.PositiveBigIntegerField(null=True)),
                ('num_injured', models.PositiveBigIntegerField(null=True)),
                ('death_injured', models.PositiveBigIntegerField(null=True)),
                ('fem_death', models.PositiveBigIntegerField(null=True)),
                ('fem_injured', models.PositiveBigIntegerField(null=True)),
                ('child_death', models.PositiveBigIntegerField(null=True)),
                ('child_injured', models.PositiveBigIntegerField(null=True)),
                ('Infra_damage', models.PositiveBigIntegerField(null=True)),
                ('Infra_destroyed', models.PositiveBigIntegerField(null=True)),
                ('incident_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incident')),
            ],
            options={
                'verbose_name': "Number of Incident's Victim",
                'verbose_name_plural': "Number of Incident's Victim",
            },
        ),
    ]
