# Generated by Django 4.0.5 on 2022-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_incident_infra_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Infra_damage',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='Infra_destroyed',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='child_death',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='child_injured',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='covid_rel',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='death_injured',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='fem_death',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='fem_injured',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='num_death',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='num_injured',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Incident_number',
        ),
    ]
