# Generated by Django 4.0.5 on 2022-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_incident_infra_damage_incident_infra_destroyed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Infra_damage',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Infra_destroyed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='child_death',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='child_injured',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='covid_rel',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='death_injured',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='fem_death',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='fem_injured',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='num_death',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='num_injured',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
