# Generated by Django 4.0.5 on 2022-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_incident_infra_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrcit_city',
            name='coordinate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='coordinate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sub_district',
            name='coordinate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
