# Generated by Django 4.0.5 on 2022-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_distrcit_city_coordinate_province_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
