# Generated by Django 4.0.5 on 2022-06-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_incident_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='date_modified',
        ),
    ]
