# Generated by Django 4.0.5 on 2022-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_incident_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
